[project]
name = "understanding-starlette"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "starlette>=0.50.0",
    "unicorn>=2.1.4",
    "uvicorn>=0.40.0",
]
